import whiteOne from '../../images/t-shirts-white.jpg';
import blackOne from '../../images/t-shirts-black.jpg';

export const categoryList = [
  {
    id: 1,
    value: 'male',
    label: '♂️ Man'
  },
  {
    id: 2,
    value: 'female',
    label: '♀️ Woman'
  },
]

export const sizeList = [
  {
    id: 1,
    value: 'XS',
    label: 'XS'
  },
  {
    id: 2,
    value: 'S',
    label: 'S'
  },
  {
    id: 3,
    value: 'M',
    label: 'M'
  },
  {
    id: 4,
    value: 'L',
    label: 'L'
  },
  {
    id: 5,
    value: 'XL',
    label: 'XL'
  },
  {
    id: 6,
    value: 'XXL',
    label: 'XXL'
  },
]

export const dataList
 = [
  {
    id: 1,
    title: 'Футболка чоловіча',
    price: 460,
    size: 'S',
    gender: 'male',
    color: 'White',
    type: 't-shirt',
    coverSrc: whiteOne,
  },
  {
    id: 2,
    title: 'Футболка чоловіча',
    price: 470,
    size: 'XS',
    gender: 'male',
    color: 'White',
    type: 't-shirt',
    coverSrc: whiteOne,
  },
  {
    id: 3,
    title: 'Футболка жіноча',
    price: 560,
    size: 'L',
    gender: 'female',
    color: 'White',
    type: 't-shirt',
    coverSrc: whiteOne,
  },
  {
    id: 4,
    title: 'Футболка жіноча',
    price: 460,
    size: 'M',
    gender: 'female',
    color: 'Black',
    type: 't-shirt',
    coverSrc: blackOne,
  },
  {
    id: 5,
    title: 'Футболка чоловіча',
    price: 660,
    size: 'XS',
    gender: 'male',
    color: 'Black',
    type: 'sweetshirt',
    coverSrc: blackOne,
  },
  {
    id: 6,
    title: 'Футболка чоловіча',
    price: 660,
    size: 'M',
    gender: 'male',
    color: 'Black',
    type: 'sweetshirt',
    coverSrc: blackOne,
  },
  {
    id: 7,
    title: 'Футболка чоловіча',
    price: 660,
    size: 'M',
    gender: 'male',
    color: 'White',
    type: 'sweetshirt',
    coverSrc: whiteOne,
  },
  {
    id: 8,
    title: 'Футболка чоловіча',
    price: 520,
    size: 'S',
    gender: 'male',
    color: 'Black',
    type: 't-shirt',
    coverSrc: blackOne,
  },
  {
    id: 9,
    title: 'Футболка жіноча',
    price: 460,
    size: 'S',
    gender: 'female',
    color: 'White',
    type: 'sweetshirt',
    coverSrc: whiteOne,
  },
  {
    id: 10,
    title: 'Футболка чоловіча',
    price: 460,
    size: 'S',
    gender: 'male',
    color: 'White',
    type: 't-shirt',
    coverSrc: whiteOne,
  },
  {
    id: 11,
    title: 'Футболка чоловіча',
    price: 530,
    size: 'S',
    gender: 'male',
    color: 'White',
    type: 't-shirt',
    coverSrc: whiteOne,
  },
  {
    id: 12,
    title: 'Футболка чоловіча',
    price: 470,
    size: 'XS',
    gender: 'male',
    color: 'White',
    type: 't-shirt',
    coverSrc: whiteOne,
  },
  {
    id: 13,
    title: 'Футболка жіноча',
    price: 560,
    size: 'L',
    gender: 'female',
    color: 'White',
    type: 't-shirt',
    coverSrc: whiteOne,
  },
  {
    id: 14,
    title: 'Футболка жіноча',
    price: 460,
    size: 'M',
    gender: 'female',
    color: 'Black',
    type: 't-shirt',
    coverSrc: blackOne,
  },
  {
    id: 15,
    title: 'Футболка чоловіча',
    price: 660,
    size: 'XS',
    gender: 'male',
    color: 'Black',
    type: 'sweetshirt',
    coverSrc: blackOne,
  },
  {
    id: 16,
    title: 'Футболка чоловіча',
    price: 660,
    size: 'M',
    gender: 'male',
    color: 'Black',
    type: 'sweetshirt',
    coverSrc: blackOne,
  },
  {
    id: 17,
    title: 'Футболка чоловіча',
    price: 660,
    size: 'M',
    gender: 'male',
    color: 'White',
    type: 'sweetshirt',
    coverSrc: whiteOne,
  },
  {
    id: 18,
    title: 'Футболка чоловіча',
    price: 520,
    size: 'S',
    gender: 'male',
    color: 'Black',
    type: 't-shirt',
    coverSrc: blackOne,
  },
  {
    id: 19,
    title: 'Футболка жіноча',
    price: 460,
    size: 'S',
    gender: 'female',
    color: 'White',
    type: 'sweetshirt',
    coverSrc: whiteOne,
  },
]